#
# Number of Users to Simulate 
#
users: 25
#
# Seconds to wait while ramping up users
#
ramp: 2
#
# Seconds to run the API load test
#
duration: 120
#
# Seconds to wait between API requests
#
wait: 1
#
# Service level agreement in Milliseconds (reports transaction that exceeds this number)
#
sla: 1000
#
# Template used to apply token to API request Headers
#
tokentemplate: "Bearer {{.}}"
#
# This is for an auth token that exists
# Note: Might be better and more secure to apply this via the -token 
# command line argument 
#
authtoken: "*** some auth token ***"
#
# URL required to obtain an authorization Token from an authentication API
# that returns a token
#
# Note: If an authorization token already exists, you won't need to use this 
# to obtain one
# 
auth:
  url: https://<authenticate URL>
  userid: xxxxx
  password: dddddd
  tokenizeusing: ","
  gettoken: "token"
  splitwith: ":"
#
# URLs to load-test
#
url:
  - POST~<URL>%201~{key1: value1, key2: value2}
  - POST~<URL>%201~key=value&key2=value2
  - GET~<URL>